services:
  mihomo:
    image: metacubex/mihomo:latest
    container_name: mihomo
    restart: always
    volumes:
      - ./config:/root/.config/mihomo
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
