#############################################################
# Filename: ~/.zshrc
#############################################################

# Init cool-dotfiles versioned zsh runtime
[ -s "$HOME/.config/zsh/init.zsh" ] && source "$HOME/.config/zsh/init.zsh"

#+++++++++++++++++++++++++++++++++++++++
# Editor & Aliases
#+++++++++++++++++++++++++++++++++++++++

alias vi=nvim
alias vim=nvim
alias ll="ls -hal"
export EDITOR=nvim

#+++++++++++++++++++++++++++++++++++++++
# USER-DEFINED Afterwards
#+++++++++++++++++++++++++++++++++++++++
